# Generated by Django 3.2.3 on 2021-06-04 15:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('url_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('duration', models.FloatField()),
                ('format', models.CharField(max_length=3)),
                ('production', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=50)),
                ('actors', models.TextField()),
                ('year', models.IntegerField()),
                ('image', models.ImageField(height_field='image_height', upload_to='media/films', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(blank=True, default='525', editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, default='260', editable=False, null=True)),
                ('trailer', models.URLField()),
                ('in_theatre', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=0)),
                ('seat', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.session')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kol_bil', models.IntegerField(default=0)),
                ('summa', models.IntegerField(default=0)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.session')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(to='films.Genre'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_name', models.CharField(max_length=20)),
                ('row', models.IntegerField(default=0)),
                ('seat', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.session')),
            ],
        ),
    ]
